# Generated by Django 3.2.9 on 2022-12-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=120),
        ),
    ]
