# Generated by Django 3.2.9 on 2022-12-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_Pic',
            field=models.ImageField(upload_to='upload/profile_pic'),
        ),
    ]
