# Generated by Django 3.2.9 on 2022-12-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0004_auto_20221231_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_Pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
