# Generated by Django 3.2.9 on 2022-12-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0005_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_Pic',
            field=models.ImageField(upload_to='media/profile_pic'),
        ),
    ]
