# Generated by Django 3.2.9 on 2023-01-03 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0007_course_session_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default=' ')),
                ('city', models.TextField(default=' ')),
                ('mobile', models.CharField(default=False, max_length=13)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('admin', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schl_mng_app.course')),
                ('session_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schl_mng_app.session_year')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
