# Generated by Django 3.2.9 on 2023-01-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0008_auto_20230103_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='dateofbirth',
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
    ]
