# Generated by Django 3.2.9 on 2023-01-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0009_auto_20230103_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dateofbirth',
            field=models.CharField(default='', max_length=100),
        ),
    ]
