# Generated by Django 3.2.9 on 2023-01-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0010_students_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
