# Generated by Django 3.2.9 on 2023-01-07 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0013_auto_20230107_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schl_mng_app.staff'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schl_mng_app.course'),
        ),
    ]
