# Generated by Django 3.2.9 on 2023-01-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0018_staff_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_feedback',
            name='feedback_reply',
            field=models.TextField(null=True),
        ),
    ]
