# Generated by Django 3.2.9 on 2023-09-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schl_mng_app', '0023_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_Pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
